
# Services
services:
  # Database
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-db
    volumes:
      - db-data:/var/lib/mysql
      - ./db-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  # WordPress
  wordpress:
    image: wordpress:latest
    container_name: ${PROJECT_NAME}-web
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    ports:
      - ${WEB_PORT_NUMBER}:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    domainname: ${PROJECT_NAME}.test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db:3306
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    links:
      - db
    environment:
      UPLOAD_LIMIT: 100M
    ports:
      - ${PHPMYADMIN_PORT_NUMBER}:80
    volumes:
      - /sessions
    depends_on:
      - db
volumes:
  db-data:
    driver: local